### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by toniash1955** [M1chelle99/AudioProcessHelper#1]
Is it possible to autostart it?

**Comment by mysticalfoxie** [comment]
I haven't worked on this project for a while but I will take a look on it. 

As far as I remembered I'm using Launch Arguments to suppress the UI. 
So it's definitely possible by adding a Batch file to your Autostart Directory.
(%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup)

I'll work over some things in this App so the AutoStart option is already in the UI.

**Comment by toniash1955** [comment]
Ok thank you!

El dl., 11 de jul. 2022, 08:18, M1chelle99 ***@***.***> va
escriure:

**Comment by mysticalfoxie** [comment]
All right, I made a recent update where the quick start feature is a lot more enhanced! 

In order to have it in the Autostart you need to...
- Create a Shortcut of the .EXE file. 
- Go to Properties of the newly created shortcut.
- Add `nogui` at the end of the Target field.
- At this point it should look like this: ![image](https://user-images.githubusercontent.com/80773420/180653514-ec43e8a8-e41d-43ce-a5ee-11dccc061363.png)
- Now move the shortcut to this location: 
   %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\
- You can rename it if you want to something like this
![image](https://user-images.githubusercontent.com/80773420/180653909-e4bd407e-44bd-4c65-8910-e36d401ed9a1.png)

And there you have it. Now the AudioProcessHelper starts with Windows!

**How it works now:**
- It increases the priorities and the core usage of your last configured programs
  So if you configured in your last session the programs `abc.exe` and `def.exe`, these programs will be manipulated on every startup. In order to change these open up the AudioProcessHelper.exe file (Not the shortcut!) and edit these processes to your desired list. 
- After Startup you will be prompted with the admin-privilege prompt from windows and after agreement your processes are modified.

PS:
I am really sorry for not building it into the UI, because this would have been a lot more comfortable but I really got a lot going on in my life and there's not much time left for projects like these. 😞😢
Hope you understand! <3

**Comment by toniash1955** [comment]
Thanks!
